apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: spring-app-container
        image: tejashwini97/spring-app:20260430-1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080		
		
        